export const APP_NAME = 'ElyXen Dine'
export const APP_TAGLINE = 'Luxury Dining, Delivered'
export const APP_DESCRIPTION = 'Premium Restaurant & Cafe Platform'

export const DELIVERY_STATUSES = [
  { key: 'preparing', label: 'Order Received', description: 'Restaurant has received your order' },
  { key: 'cooking', label: 'Being Prepared', description: 'Chef is preparing your meal' },
  { key: 'picked_up', label: 'Picked Up', description: 'Rider has picked up your order' },
  { key: 'on_the_way', label: 'On The Way', description: 'Your order is heading to you' },
  { key: 'delivered', label: 'Delivered', description: 'Enjoy your meal!' },
] as const

export const ORDER_STATUSES = {
  pending: { label: 'Pending', color: 'yellow' },
  confirmed: { label: 'Confirmed', color: 'blue' },
  preparing: { label: 'Preparing', color: 'orange' },
  cooking: { label: 'Cooking', color: 'orange' },
  picked_up: { label: 'Picked Up', color: 'purple' },
  on_the_way: { label: 'On The Way', color: 'indigo' },
  delivered: { label: 'Delivered', color: 'green' },
  cancelled: { label: 'Cancelled', color: 'red' },
} as const

export const RESERVATION_STATUSES = {
  pending: { label: 'Pending', color: 'yellow' },
  confirmed: { label: 'Confirmed', color: 'green' },
  cancelled: { label: 'Cancelled', color: 'red' },
  completed: { label: 'Completed', color: 'gray' },
} as const

export const TIME_SLOTS = [
  '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM',
  '01:00 PM', '01:30 PM',
  '02:00 PM', '02:30 PM',
  '06:00 PM', '06:30 PM',
  '07:00 PM', '07:30 PM',
  '08:00 PM', '08:30 PM',
  '09:00 PM', '09:30 PM',
]

export const CUISINE_TYPES = [
  'All',
  'Italian',
  'Japanese',
  'Indian',
  'Chinese',
  'American',
  'Mediterranean',
  'Thai',
  'Mexican',
  'French',
  'Middle Eastern',
  'Korean',
]

export const PRICE_RANGES = ['$', '$$', '$$$', '$$$$']

export const PAYMENT_METHODS = [
  { id: 'card', label: 'Credit/Debit Card', icon: 'CreditCard' },
  { id: 'cash', label: 'Cash on Delivery', icon: 'Banknote' },
  { id: 'wallet', label: 'Digital Wallet', icon: 'Wallet' },
]

export const SORT_OPTIONS = [
  { value: 'rating', label: 'Highest Rated' },
  { value: 'delivery_time', label: 'Fastest Delivery' },
  { value: 'delivery_fee', label: 'Lowest Delivery Fee' },
  { value: 'price_asc', label: 'Price: Low to High' },
  { value: 'price_desc', label: 'Price: High to Low' },
]

export const FOOD_CATEGORIES = [
  { id: 'all', name: 'All', emoji: '🍽️' },
  { id: 'starters', name: 'Starters', emoji: '🥗' },
  { id: 'mains', name: 'Mains', emoji: '🍝' },
  { id: 'burgers', name: 'Burgers', emoji: '🍔' },
  { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  { id: 'sushi', name: 'Sushi', emoji: '🍱' },
  { id: 'desserts', name: 'Desserts', emoji: '🍰' },
  { id: 'drinks', name: 'Drinks', emoji: '🍹' },
  { id: 'coffee', name: 'Coffee', emoji: '☕' },
]

export const MOCK_RESTAURANTS = [
  {
    id: '1',
    name: 'Sakura Fine Japanese',
    description: 'An exquisite journey through authentic Japanese cuisine, featuring premium Wagyu and fresh sashimi',
    cuisine_type: 'Japanese',
    rating: 4.9,
    review_count: 2847,
    price_range: '$$$',
    image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1200&q=80',
    address: '123 Cherry Blossom Ave',
    city: 'New York',
    phone: '+1 (212) 555-0101',
    email: 'info@sakurafine.com',
    is_open: true,
    delivery_time: '25-35 min',
    delivery_fee: 2.99,
    minimum_order: 25,
    is_featured: true,
    tags: ['Sushi', 'Ramen', 'Wagyu', 'Premium'],
  },
  {
    id: '2',
    name: 'La Bella Trattoria',
    description: 'Authentic Italian recipes passed down through generations, crafted with imported ingredients',
    cuisine_type: 'Italian',
    rating: 4.8,
    review_count: 1923,
    price_range: '$$$',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80',
    address: '456 Via Roma',
    city: 'New York',
    phone: '+1 (212) 555-0102',
    email: 'ciao@labellatrattoria.com',
    is_open: true,
    delivery_time: '30-45 min',
    delivery_fee: 3.99,
    minimum_order: 30,
    is_featured: true,
    tags: ['Pasta', 'Pizza', 'Risotto', 'Wine'],
  },
  {
    id: '3',
    name: 'The Golden Spice',
    description: 'A symphony of aromatic spices and bold flavors from across the Indian subcontinent',
    cuisine_type: 'Indian',
    rating: 4.7,
    review_count: 3156,
    price_range: '$$',
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1200&q=80',
    address: '789 Spice Lane',
    city: 'New York',
    phone: '+1 (212) 555-0103',
    email: 'hello@goldenspice.com',
    is_open: true,
    delivery_time: '20-30 min',
    delivery_fee: 1.99,
    minimum_order: 20,
    is_featured: true,
    tags: ['Curry', 'Tandoor', 'Biryani', 'Vegetarian'],
  },
  {
    id: '4',
    name: 'Le Petit Bistro',
    description: 'Classic French culinary artistry reimagined for the modern palate',
    cuisine_type: 'French',
    rating: 4.8,
    review_count: 1456,
    price_range: '$$$$',
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80',
    address: '321 Boulevard Haussmann',
    city: 'New York',
    phone: '+1 (212) 555-0104',
    email: 'bonjour@lepetitbistro.com',
    is_open: false,
    delivery_time: '35-50 min',
    delivery_fee: 4.99,
    minimum_order: 50,
    is_featured: false,
    tags: ['Croissants', 'Wine', 'Fine Dining', 'Brunch'],
  },
  {
    id: '5',
    name: 'Dragon Palace',
    description: 'Authentic Cantonese dim sum and Peking duck in an opulent setting',
    cuisine_type: 'Chinese',
    rating: 4.6,
    review_count: 2341,
    price_range: '$$',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=1200&q=80',
    address: '654 Dragon Street',
    city: 'New York',
    phone: '+1 (212) 555-0105',
    email: 'info@dragonpalace.com',
    is_open: true,
    delivery_time: '25-40 min',
    delivery_fee: 2.49,
    minimum_order: 20,
    is_featured: true,
    tags: ['Dim Sum', 'Peking Duck', 'Noodles', 'Tea'],
  },
  {
    id: '6',
    name: 'Athens Mediterranean',
    description: 'Fresh Mediterranean flavors with hand-picked ingredients from the Greek coast',
    cuisine_type: 'Mediterranean',
    rating: 4.7,
    review_count: 1788,
    price_range: '$$$',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    cover_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80',
    address: '987 Olive Grove Rd',
    city: 'New York',
    phone: '+1 (212) 555-0106',
    email: 'yamas@athenmed.com',
    is_open: true,
    delivery_time: '30-40 min',
    delivery_fee: 3.49,
    minimum_order: 25,
    is_featured: false,
    tags: ['Gyros', 'Hummus', 'Seafood', 'Healthy'],
  },
]

export const MOCK_FOODS = [
  {
    id: '1',
    name: 'Premium Wagyu Ramen',
    description: 'Rich tonkotsu broth with A5 Wagyu beef slices, soft-boiled egg, bamboo shoots and nori',
    price: 34.99,
    image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
    category_id: 'mains',
    restaurant_id: '1',
    is_available: true,
    is_featured: true,
    is_vegetarian: false,
    is_spicy: false,
    rating: 4.9,
    review_count: 847,
    preparation_time: 20,
    calories: 680,
    tags: ['Wagyu', 'Ramen', 'Premium'],
  },
  {
    id: '2',
    name: 'Dragon Roll Platter',
    description: '12 pieces of our signature dragon roll with avocado, shrimp tempura and spicy mayo',
    price: 28.99,
    image_url: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80',
    category_id: 'sushi',
    restaurant_id: '1',
    is_available: true,
    is_featured: true,
    is_vegetarian: false,
    is_spicy: true,
    rating: 4.8,
    review_count: 623,
    preparation_time: 15,
    calories: 520,
    tags: ['Sushi', 'Roll', 'Spicy'],
  },
  {
    id: '3',
    name: 'Truffle Carbonara',
    description: 'Hand-rolled pasta with black truffle, guanciale, pecorino romano and egg yolk',
    price: 26.99,
    image_url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80',
    category_id: 'mains',
    restaurant_id: '2',
    is_available: true,
    is_featured: true,
    is_vegetarian: false,
    is_spicy: false,
    rating: 4.9,
    review_count: 1156,
    preparation_time: 18,
    calories: 890,
    tags: ['Pasta', 'Truffle', 'Creamy'],
  },
  {
    id: '4',
    name: 'Margherita Napoletana',
    description: 'Wood-fired Neapolitan pizza with San Marzano tomatoes, buffalo mozzarella and fresh basil',
    price: 22.99,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80',
    category_id: 'pizza',
    restaurant_id: '2',
    is_available: true,
    is_featured: false,
    is_vegetarian: true,
    is_spicy: false,
    rating: 4.7,
    review_count: 934,
    preparation_time: 25,
    calories: 720,
    tags: ['Pizza', 'Vegetarian', 'Classic'],
  },
  {
    id: '5',
    name: 'Butter Chicken Royale',
    description: 'Slow-cooked tender chicken in rich tomato-cream sauce with aromatic spices',
    price: 18.99,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
    category_id: 'mains',
    restaurant_id: '3',
    is_available: true,
    is_featured: true,
    is_vegetarian: false,
    is_spicy: true,
    rating: 4.8,
    review_count: 2341,
    preparation_time: 20,
    calories: 650,
    tags: ['Curry', 'Spicy', 'Popular'],
  },
  {
    id: '6',
    name: 'Matcha Tiramisu',
    description: 'Japanese-Italian fusion dessert with ceremonial matcha, mascarpone and ladyfinger biscuits',
    price: 12.99,
    image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    category_id: 'desserts',
    restaurant_id: '1',
    is_available: true,
    is_featured: true,
    is_vegetarian: true,
    is_spicy: false,
    rating: 4.9,
    review_count: 445,
    preparation_time: 5,
    calories: 380,
    tags: ['Dessert', 'Matcha', 'Fusion'],
  },
  {
    id: '7',
    name: 'Peking Duck',
    description: 'Whole roasted Beijing duck with crispy skin, served with pancakes, hoisin and spring onion',
    price: 42.99,
    image_url: 'https://images.unsplash.com/photo-1623689046286-01bce1e95ab7?w=600&q=80',
    category_id: 'mains',
    restaurant_id: '5',
    is_available: true,
    is_featured: true,
    is_vegetarian: false,
    is_spicy: false,
    rating: 4.7,
    review_count: 812,
    preparation_time: 35,
    calories: 1200,
    tags: ['Duck', 'Peking', 'Premium'],
  },
  {
    id: '8',
    name: 'Greek Mezze Platter',
    description: 'Curated selection of hummus, tzatziki, spanakopita, olives and warm pita bread',
    price: 24.99,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    category_id: 'starters',
    restaurant_id: '6',
    is_available: true,
    is_featured: false,
    is_vegetarian: true,
    is_spicy: false,
    rating: 4.6,
    review_count: 567,
    preparation_time: 10,
    calories: 480,
    tags: ['Vegetarian', 'Sharing', 'Mediterranean'],
  },
]

export const MOCK_TESTIMONIALS = [
  {
    id: '1',
    name: 'Alexandra Chen',
    role: 'Food Critic, NYT',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    rating: 5,
    comment: 'ElyXen Dine has completely transformed how I discover and order premium dining experiences. The interface is stunning and the quality is consistently exceptional.',
    restaurant: 'Sakura Fine Japanese',
  },
  {
    id: '2',
    name: 'Marcus Williams',
    role: 'CEO, TechVentures',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    rating: 5,
    comment: 'The reservation system is flawless. I can book a table for important business dinners in seconds. The delivery tracking is like nothing else on the market.',
    restaurant: 'Le Petit Bistro',
  },
  {
    id: '3',
    name: 'Sofia Rodriguez',
    role: 'Interior Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    rating: 5,
    comment: 'As someone who appreciates aesthetics, ElyXen Dine\'s design is impeccable. The food quality matches the platform\'s premium feel. Absolutely love it.',
    restaurant: 'La Bella Trattoria',
  },
  {
    id: '4',
    name: 'James Okafor',
    role: 'Executive Chef',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    rating: 5,
    comment: 'From a restaurant perspective, the management dashboard is incredibly powerful. Order management and analytics have streamlined our entire operation.',
    restaurant: 'Athens Mediterranean',
  },
]
